{{- $root := . }}
{{- range $name, $values := .Values.backend.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nestjs.fullname" $root }}-{{ $name }}
  labels: {{ include "nestjs.labels" (dict "context" . "component" .Values.backend.config.name "name" .Values.backend.config.name) | nindent 4 }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}