{{- $root := . }}
{{- range $name, $values := .Values.backend.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nestjs.fullname" $root }}-{{ $name | camelcase | kebabcase }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}