apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nestjs.fullname" . }}
  labels: {{ include "nestjs.labels" (dict "context" . "component" .Values.backend.config.name "name" .Values.backend.config.name) | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.localDatabase.enabled }}
  dbHost: {{ include "postgresql.primary.fullname" .Subcharts.postgresql | b64enc}}
  dbPort: {{ .Values.global.postgresql.service.ports.postgresql | toString | b64enc}}
  dbUsername: {{ .Values.global.postgresql.auth.username | b64enc }}
  dbPassword: {{ .Values.global.postgresql.auth.password | b64enc}}
  dbDatabaseName: {{ .Values.global.postgresql.auth.database | b64enc }}
  {{- else }}
  dbHost: {{ .Values.backend.remoteDatabase.host | b64enc }}
  dbPort: {{ .Values.backend.remoteDatabase.port | b64enc }}
  dbUsername: {{ .Values.backend.remoteDatabase.username | b64enc }}
  dbPassword: {{ .Values.backend.remoteDatabase.password | b64enc }}
  dbDatabaseName: {{ .Values.backend.remoteDatabase.name | b64enc }}
  {{- end -}}